<?php
require_once(t3lib_extMgm::extPath('nr_cdn').'class.user_t3libpagerenderer.php');
/**
 * Test class for nr_cdn.
 * Generated by PHPUnit on 2010-08-25 at 08:31:45.
 */
class PageRendererTest extends PHPUnit_Framework_TestCase
{
    public function setUp()
    {
    	$GLOBALS['TSFE']->tmpl->setup['config.']['nr_cdn.']['URL'] = 'UnittestUrl/';
    }

    public function tearDown()
    {
    	unset($GLOBALS['TSFE']->tmpl->setup['config.']['nr_cdn.']);
    }

    public function testRenderPreProcess()
    {
        $arJsLibs = array(
            'fileadmin/bla' => array(),
            'typo3temp/bla' => array(),
        );
        $arJsFiles = array(
            'fileadmin/bla' => array(),
            'typo3temp/bla' => array(),
        );
        $arJsFooterFiles = array(
            'fileadmin/bla' => array(),
            'typo3temp/bla' => array(),
        );
        $arCssFiles = array(
            'fileadmin/bla' => array(),
            'typo3temp/bla' => array(),
        );
        $class = new user_t3libpagerenderer();
        $arTest = array(
            'jsLibs' => &$arJsLibs,
            'jsFiles' => &$arJsFiles,
            'jsFooterFiles' => &$arJsFooterFiles,
            'cssFiles' => &$arCssFiles,
        );
        $class->renderPreProcess($arTest, null);

        $this->assertTrue(
        	isset($arTest['jsLibs']['UnittestUrl/fileadmin/bla']),
        	'"fileadmin/" path must be prefixed with "UnittestUrl/"'
        );
        $this->assertTrue(
        	isset($arTest['jsLibs']['typo3temp/bla']),
        	'"fileadmin/" path must be prefixed with "UnittestUrl/"'
        );

        $this->assertTrue(
        	isset($arTest['jsFiles']['UnittestUrl/fileadmin/bla']),
        	'"fileadmin/" path must be prefixed with "UnittestUrl/"'
        );
        $this->assertTrue(
        	isset($arTest['jsFiles']['typo3temp/bla']),
        	'"fileadmin/" path must be prefixed with "UnittestUrl/"'
        );

        $this->assertTrue(
        	isset($arTest['jsFooterFiles']['UnittestUrl/fileadmin/bla']),
        	'"fileadmin/" path must be prefixed with "UnittestUrl/"'
        );
        $this->assertTrue(
        	isset($arTest['jsFooterFiles']['typo3temp/bla']),
        	'"fileadmin/" path must be prefixed with "UnittestUrl/"'
        );

        $this->assertTrue(
        	isset($arTest['cssFiles']['UnittestUrl/fileadmin/bla']),
        	'"fileadmin/" path must be prefixed with "UnittestUrl/"'
        );
        $this->assertTrue(
        	isset($arTest['cssFiles']['typo3temp/bla']),
        	'"fileadmin/" path must be prefixed with "UnittestUrl/"'
        );
    }
}

?>