<?php
require_once(t3lib_extMgm::extPath('nr_cdn').'class.ux_tslib_content.php');
/**
 * Test class for nr_cdn.
 * Generated by PHPUnit on 2010-08-25 at 08:31:45.
 */
class UxContentTest extends PHPUnit_Framework_TestCase
{
    public function tx_dummyUserFunc()
    {

        return 'foo';
    }



    public function testUser()
    {
        $GLOBALS['TSFE']->tmpl->setup['config.']['nr_cdn.'] = array();
        $GLOBALS['TSFE']->TYPO3_CONF_VARS['FE']['userFuncClassPrefix'] = '';
        $conf = array(
            'includeLibs' => null,
            'userFunc' => 'UxContentTest->tx_dummyUserFunc'
        );
        $uxc = new ux_tslib_cObj();

        $this->assertSame('foo', $uxc->USER($conf));
    }


    public function testMultimedia()
    {

        $ucx = $this->getMock(
            'ux_tslib_cObj',
            array('MULTIMEDIA')
        );
        $ucx->expects($this->any())
            ->method('MULTIMEDIA')
            ->will($this->returnValue('test'));

        $this->assertSame('test',$ucx->MULTIMEDIA(array()));

    }

    public function testCImage()
    {
        $ucx = $this->getMock(
            'ux_tslib_cObj',
            array('cImage')
        );
        $ucx->expects($this->any())
            ->method('cImage')
            ->will($this->returnValue('test'));

        $this->assertSame('test', $ucx->cImage('', array()));

    }

    public function testSetTypo3AbsRefPrefix()
    {
        $GLOBALS['TSFE']->absRefPrefix = 'ABC';

        $this->assertSame('ABC', $GLOBALS['TSFE']->absRefPrefix);
    }

}